image: node:latest

cache:
    paths:
        - node_modules/

test:
    stage: test
    script:
        - yarn install
        - yarn lint
        - yarn build

pages:
    stage: deploy
    script:
        - yarn install
        - yarn build
        - rm public/ -r
        - mv dist public
    artifacts:
        paths:
            - public
    only:
        - master
