image: node:latest

cache:
    paths:
        - node_modules/

# test:
#     stage: test
#     script:
#         - yarn install
#         - yarn lint
#         - yarn coverage
#     artifacts:
#         reports:
#             cobertura: coverage/cobertura-coverage.xml

pages:
    stage: deploy
    script:
        - yarn install
        - yarn build
        - rm public/ -r
        - mv dist public
    artifacts:
        paths:
            - public
    only:
        - master
