name: Website Deployment
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build
    - uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: dist/*

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v1
